# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f82e22bbce11e17c0cbd46e7d32e5ee77bcf2cc8d0654ec8e34fb2dfe834c283d5bcdbbc567720ca53271e3f4e946b7550564fd03e4836880dbcf37d3651d07

test:
  secret_key_base: 145546ceddc422ec21c69cbc3d78edc343b6dce688ddb7b19cb7011f48f448f23e9026532f9aa3da18b7209e78f95e806347a4d495d074863048b769327caaa4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
